apiVersion: apps/v1
kind: Deployment
metadata:
  name: shikhawf
  labels:
    app: shikhawf
    kubernetes.azure.com/generator: devhub
  namespace: demotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shikhawf
  template:
    metadata:
      labels:
        app: shikhawf
    spec:
      containers:
        - name: shikhawf
          image: acrworkflow1716915490799.azurecr.io/image-workflow-1716915490799:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
