apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoday
  labels:
    app: demoday
    kubernetes.azure.com/generator: devhub
  namespace: demonamesp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoday
  template:
    metadata:
      labels:
        app: demoday
    spec:
      containers:
        - name: demoday
          image: acrworkflow1716915947633.azurecr.io/image-workflow-1716915947633:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
