apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718912158688
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: demo1
          image: acrworkflow1718912158688.azurecr.io/image-workflow-1718912158688:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
