apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdasdasdas
  labels:
    app: asdasdasdas
  namespace: namespace-workflow-1715369558336
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdasdasdas
  template:
    metadata:
      labels:
        app: asdasdasdas
    spec:
      containers:
        - name: asdasdasdas
          image: acrworkflow1715369558336.azurecr.io/image-workflow-1715369558336:latest
          ports:
            - containerPort: 5000