apiVersion: apps/v1
kind: Deployment
metadata:
  name: Demo
  labels:
    app: Demo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718839792328
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Demo
  template:
    metadata:
      labels:
        app: Demo
    spec:
      containers:
        - name: Demo
          image: acrworkflow1718839792328.azurecr.io/image-workflow-1718839792328:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
