apiVersion: v1
kind: Service
metadata:
  name: testworkflow
  namespace: namespace-workflow-1706831693082
spec:
  type: LoadBalancer
  selector:
    app: testworkflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000