apiVersion: v1
kind: Service
metadata:
  name: demo1
  namespace: namespace-workflow-1718912158688
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demo1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000