apiVersion: v1
kind: Service
metadata:
  name: rockpaperwf
  namespace: namespace-workflow-1714494520795
spec:
  type: LoadBalancer
  selector:
    app: rockpaperwf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000