apiVersion: v1
kind: Service
metadata:
  name: new-workflow
  namespace: demo-child
spec:
  type: LoadBalancer
  selector:
    app: new-workflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000