apiVersion: v1
kind: Service
metadata:
  name: shikhawf
  namespace: demotest
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: shikhawf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000