apiVersion: v1
kind: Service
metadata:
  name: autodeploytest
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: autodeploytest
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000