apiVersion: v1
kind: Service
metadata:
  name: Demo
  namespace: namespace-workflow-1718839792328
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: Demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000