apiVersion: v1
kind: Service
metadata:
  name: demoday
  namespace: namespace-workflow-1718927813727
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demoday
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000