apiVersion: v1
kind: Service
metadata:
  name: asdasdasdas
  namespace: namespace-workflow-1715369558336
spec:
  type: LoadBalancer
  selector:
    app: asdasdasdas
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000